= COMP1200: Computer Organization

Midterm is on February 11.

== Resources

* http://sourceforge.net/projects/circuit/files/latest/download[Download Logisim]
* https://github.com/lawrancej/COMP1200-2016/blob/master/Circuits/cpu-16bit-isa.adoc[CPU instruction set]

NOTE: For the folks on Mac, open Terminal (Applications -> Utilities -> Terminal)

----
cd ~/Downloads
java -jar Logisim.app/Contents/Resources/Java/logisim.jar
----

== Agenda

[horizontal]
January 6:: https://github.com/lawrancej/COMP1200-2016/blob/master/Lectures/[Introduce yourself, About this course]
January 7:: https://github.com/lawrancej/COMP1200-2016/blob/master/Lectures/[Number bases, conversions]
January 8:: https://github.com/lawrancej/COMP1200-2016/blob/master/Git.adoc[Lab 0: Setup git]
January 11:: https://github.com/lawrancej/COMP1200-2016/blob/master/Lectures/[Logic expressions, truth tables]
January 13:: Introduction to Logisim
January 14:: https://github.com/lawrancej/COMP1200-2016/blob/master/Labs/[Lab 1: Discrete math review]
January 15:: https://github.com/lawrancej/COMP1200-2016/blob/master/Lectures/[Boolean algebra, Gray codes, K-Maps]
January 20:: https://github.com/lawrancej/COMP1200-2016/blob/master/Lectures/[Multiplexers and ROMs to implement combinational logic].
January 21:: https://github.com/lawrancej/COMP1200-2016/blob/master/Labs/[Lab 2: Circuit implementation]
January 22:: https://github.com/lawrancej/COMP1200-2016/blob/master/Lectures/[Sequential logic].
January 25:: https://github.com/lawrancej/COMP1200-2016/blob/master/Lectures/[State machines].
January 27:: https://github.com/lawrancej/COMP1200-2016/blob/master/Lectures/[State machine example]
January 28:: https://github.com/lawrancej/COMP1200-2016/blob/master/Labs/[Lab 3: State machine implementation]
January 29:: https://github.com/lawrancej/COMP1200-2016/blob/master/Lectures/[More state machines].
February 1:: https://github.com/lawrancej/COMP1200-2016/blob/master/Lectures/[CPU walkthrough].
February 3:: https://github.com/lawrancej/COMP1200-2016/blob/master/Lectures/[Programming the CPU]
February 4:: https://github.com/lawrancej/COMP1200-2016/blob/master/Labs/[Lab 4: Machine language programming]
February 5:: Class canceled
February 8:: Class canceled
February 10:: https://github.com/lawrancej/COMP1200-2016/blob/master/Exams/[Midterm practice]
February 11:: Midterm
February 12:: https://github.com/lawrancej/COMP1200-2016/blob/master/Lectures/[About your machine]
February 15:: President's day (observed)
February 17:: Get midterms back.
