= Practice solutions

== Another practice midterm solutions

Show 0o1573006755 in binary, and then convert from binary to hexadecimal

----
0b1101111011000000110111101101
0xDEC0DED
----

Show −42 in binary using two’s complement. Show place values.

----
-64 32 16 8 4 2 1 Place values
  0  1  0 1 0 1 0  42
  1  0  1 0 1 1 0 -42
----

Perform the following subtraction operation using two’s complement.

----
-64 32 16 8 4 2 1  Place values
  1  1  0 1 0 0 0 Carry
  0  1  1 0 1 1 1  A
+ 1  1  1 0 1 0 0  -B
 ---------------------
  0  1  0 1 0 1 1  Sum
----

Perform the following addition operation.

----
64 32 16 8 4 2 1 Place values
   1  1 1 0 0 0 Carry
   1  0 0 1 0 0 A
+  0  1 1 1 1 1 B
 ------------
 1 0  0 0 0 1 1 Sum
----

Fill in the blanks in this table by showing the dual form of the law.

[horizontal]
Identity:: a + 1 = 1
Absorption:: a * (a + b) = a
Complement:: a + a' = 1

Using the laws of Boolean algebra, show b + a + a · b = 1. Cite laws as you apply them.

[horizontal]
Original:: b' + a' + a * b = 1
Distribute:: b' + (a' + a) * (a' + b) = 1
Complement:: b' + 1 * (a' + b) = 1
Identity:: b' + (a' + b) = 1
Commutativity:: b' + b + a' = 1
Complement, Identity:: 1 + a' = 1

Let A be a 3-bit binary number. Design a circuit that determines whether A is even (divisible by two). For example, since 0 is even, when A = 0b000, the circuit should output 1.

Draw the truth table for this circuit. Label inputs as A2,A1,A0. Label the output as even.

> [cols="4"]
|===
|A2|A1|A0|even

|0|0|0|1
|0|0|1|0
|0|1|0|1
|0|1|1|0
|1|0|0|1
|1|0|1|0
|1|1|0|1
|1|1|1|0
|===

Write out the logic expression for this circuit. Simplify all the way.

> A0'

Implement this circuit using a 4-1 MUX, even though it’s a tad ridiculous. Label input and select lines with appropriate variables and expressions.

> All inputs are A0'. The select line 0 is A1, select line 1 is A2.
